# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "BOARDPERIODS" ("ID" BIGSERIAL PRIMARY KEY,"BOARDID" VARCHAR(254) NOT NULL,"STARTDATE" BIGINT NOT NULL,"ENDDATE" BIGINT NOT NULL,"PERIODINDAYS" INTEGER NOT NULL);
create table "DAILYPOINTS" ("ID" BIGSERIAL PRIMARY KEY,"BOARDID" VARCHAR(254) NOT NULL,"DATE" BIGINT NOT NULL,"SCOPE" INTEGER NOT NULL,"PROGRESS" INTEGER NOT NULL,"FINISHED" INTEGER NOT NULL);
create table "USERS" ("ID" BIGSERIAL,"EMAIL" VARCHAR(254) NOT NULL PRIMARY KEY,"USERNAME" VARCHAR(254),"PASSWORD" BYTEA NOT NULL,"APPKEY" VARCHAR(254),"APPTOKEN" VARCHAR(254));

# --- !Downs

drop table "USERS";
drop table "DAILYPOINTS";
drop table "BOARDPERIODS";

