# --- !Ups

create table "BOARDPERIODS" ("ID" BIGSERIAL PRIMARY KEY,"BOARDID" VARCHAR(254) NOT NULL,"STARTDATE" BIGINT NOT NULL,"ENDDATE" BIGINT NOT NULL,"PERIODINDAYS" INTEGER NOT NULL);
create table "DAILYPOINTS" ("ID" BIGSERIAL PRIMARY KEY,"BOARDID" VARCHAR(254) NOT NULL,"DATE" BIGINT NOT NULL,"SCOPE" INTEGER NOT NULL,"PROGRESS" INTEGER NOT NULL,"FINISHED" INTEGER NOT NULL);

# --- !Downs

#drop table "DAILYPOINTS";
#drop table "BOARDPERIODS";

